---
abstract: 'Biber is a much-augmented bibtex replacement for biblatex users'
author:
  - 'Philip Kime <Philip@kime.org.uk>'
build_requires:
  Config::AutoConf: '0.15'
  ExtUtils::LibBuilder: '0.02'
  File::Which: '0'
  Test::Differences: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: biblatex-biber
provides:
  Biber:
    file: lib/Biber.pm
  Biber::Config:
    file: lib/Biber/Config.pm
    version: '2.4'
  Biber::Constants:
    file: lib/Biber/Constants.pm
  Biber::DataModel:
    file: lib/Biber/DataModel.pm
  Biber::Entries:
    file: lib/Biber/Entries.pm
  Biber::Entry:
    file: lib/Biber/Entry.pm
  Biber::Entry::Name:
    file: lib/Biber/Entry/Name.pm
  Biber::Entry::Names:
    file: lib/Biber/Entry/Names.pm
  Biber::Input::file::biblatexml:
    file: lib/Biber/Input/file/biblatexml.pm
  Biber::Input::file::bibtex:
    file: lib/Biber/Input/file/bibtex.pm
  Biber::Input::file::ris:
    file: lib/Biber/Input/file/ris.pm
  Biber::Internals:
    file: lib/Biber/Internals.pm
  Biber::LaTeX::Recode:
    file: lib/Biber/LaTeX/Recode.pm
  Biber::Output::base:
    file: lib/Biber/Output/base.pm
  Biber::Output::bbl:
    file: lib/Biber/Output/bbl.pm
  Biber::Output::biblatexml:
    file: lib/Biber/Output/biblatexml.pm
  Biber::Output::bibtex:
    file: lib/Biber/Output/bibtex.pm
  Biber::Output::dot:
    file: lib/Biber/Output/dot.pm
  Biber::Output::test:
    file: lib/Biber/Output/test.pm
  Biber::Section:
    file: lib/Biber/Section.pm
  Biber::Sections:
    file: lib/Biber/Sections.pm
  Biber::SortList:
    file: lib/Biber/SortList.pm
  Biber::SortLists:
    file: lib/Biber/SortLists.pm
  Biber::UCollate:
    file: lib/Biber/UCollate.pm
  Biber::Utils:
    file: lib/Biber/Utils.pm
requires:
  Business::ISBN: '0'
  Business::ISMN: '0'
  Business::ISSN: '0'
  Class::Accessor: '0'
  Data::Compare: '0'
  Data::Dump: '0'
  Data::Uniqid: '0'
  Date::Simple: '0'
  Encode::EUCJPASCII: '0'
  Encode::HanExtra: '0'
  Encode::JIS2K: '0'
  File::Slurp: '0'
  IPC::Cmd: '0'
  IPC::Run3: '0'
  LWP::Protocol::https: '0'
  LWP::Simple: '0'
  List::AllUtils: '0'
  List::MoreUtils: '0'
  List::MoreUtils::XS: '0'
  Log::Log4perl: '0'
  Mozilla::CA: '20141217'
  Regexp::Common: '0'
  Text::BibTeX: '0.71'
  Text::Roman: '0'
  URI: '0'
  Unicode::Collate: '1.14'
  Unicode::GCString: '0'
  Unicode::Normalize: '1.25'
  XML::LibXML: '1.7'
  XML::LibXML::Simple: '0'
  XML::LibXSLT: '0'
  XML::Writer: '0'
  autovivification: '0'
  perl: v5.16.0
resources:
  license: http://dev.perl.org/licenses/
version: '2.4'
